### ISSUE TITLE
Example doesn't work

### ISSUE THREAD

**Issue by tschmidtb51** [secvisogram/csaf-validator-lib#40]
The README lists the example:
```
import validate from '../csaf-validator-lib/validate.js'

const document = '{}'
const tests = [
  {
    type: 'preset',
    name: 'mandatory'
  },
  {
    type: 'test',
    name: 'optionalTest_6_2_1'
  }
]

const result = await validate(tests, document)
```

However, that does not work for me. It throws an error:
```
file:///anywhere/csaf-validator-lib/lib/validate.js:11
    const result = await test(doc)
                         ^

TypeError: test is not a function
    at default (file:///anywhere/csaf-validator-lib/lib/validate.js:11:26)
    at file:///anywhere/csaf-validator-lib/testing.js:15:22
    at ModuleJob.run (internal/modules/esm/module_job.js:183:25)
    at async Loader.import (internal/modules/esm/loader.js:178:24)
    at async Object.loadESM (internal/process/esm_loader.js:68:5)
    at async handleMainPromise (internal/modules/run_main.js:59:12)
```

Based on a quick search, I guess the tuple of `type`and `name` isn't implemented here. Correct?

**Comment by domachine** [comment]
Thank very much for checking this. This is actually an outdated API. I missed to update this example. Fixin' it right now :)
